# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Run tests
        run: |
          npm ci
          npm run test:ci
      - name: Upload test result artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ./junit.xml
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: ./      
      - name: Convert xml to json and staore as variable
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: xml2json
        with:
          path: './junit.xml'
          from: 'xml'
          to: 'json'
      - name: Send test results for rating
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.RATING_URL }}
          webhook_secret: ${{ secrets.RATING_SECRET }}
          data: ${{steps.xml2json.outputs.data}}
